### ISSUE TITLE
observer.remove vs .disconnect

### ISSUE THREAD

**Issue by toklok** [andydavies/tag-timing-snippets#1]
in https://github.com/andydavies/tag-timing-snippets/blob/main/anti-flicker/google-optimize.md you have`observer.remove`

is it suppose to be `observer.disconnect`?

I didn't see a `remove` in the MDN

https://developer.mozilla.org/en-US/docs/Web/API/MutationObserver/MutationObserver

**Comment by andydavies** [comment]
Yeh, I think you're right - I get a mental block on observer.disconnect and frequently use remove instead!

Will fix

**Comment by andydavies** [comment]
Fixed - only the Optimize one was wrong!
